// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes the Build step of the function that builds a container from the
/// given source.
public struct BuildConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The Cloud Build name of the latest successful deployment of
  /// the function.
  public var name: Swift.String = Swift.String()

  /// The Cloud Storage bucket URI where the function source code is located.
  public var sourceLocation: Swift.String = Swift.String()

  /// Optional. The name of the function (as defined in source code) that will be
  /// executed. Defaults to the resource name suffix, if not specified. For
  /// backward compatibility, if function with given name is not found, then the
  /// system will try to use function named "function".
  public var functionTarget: Swift.String = Swift.String()

  /// Optional. Artifact Registry URI to store the built image.
  public var imageUri: Swift.String = Swift.String()

  /// Optional. The base image used to build the function.
  public var baseImage: Swift.String = Swift.String()

  /// Optional. Sets whether the function will receive automatic base image
  /// updates.
  public var enableAutomaticUpdates: Swift.Bool = Swift.Bool()

  /// Optional. Name of the Cloud Build Custom Worker Pool that should be used to
  /// build the Cloud Run function. The format of this field is
  /// `projects/{project}/locations/{region}/workerPools/{workerPool}` where
  /// `{project}` and `{region}` are the project id and region respectively where
  /// the worker pool is defined and `{workerPool}` is the short name of the
  /// worker pool.
  public var workerPool: Swift.String = Swift.String()

  /// Optional. User-provided build-time environment variables for the function
  public var environmentVariables: [Swift.String: Swift.String] = [:]

  /// Optional. Service account to be used for building the container. The format
  /// of this field is
  /// `projects/{projectId}/serviceAccounts/{serviceAccountEmail}`.
  public var serviceAccount: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BuildConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BuildConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let sourceLocation = CodingKeys(stringValue: "sourceLocation")
    static let functionTarget = CodingKeys(stringValue: "functionTarget")
    static let imageUri = CodingKeys(stringValue: "imageUri")
    static let baseImage = CodingKeys(stringValue: "baseImage")
    static let enableAutomaticUpdates = CodingKeys(stringValue: "enableAutomaticUpdates")
    static let workerPool = CodingKeys(stringValue: "workerPool")
    static let environmentVariables = CodingKeys(stringValue: "environmentVariables")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "sourceLocation",
      "functionTarget",
      "imageUri",
      "baseImage",
      "enableAutomaticUpdates",
      "workerPool",
      "environmentVariables",
      "serviceAccount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceLocation) {
      self.sourceLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .functionTarget) {
      self.functionTarget = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageUri) {
      self.imageUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .baseImage) {
      self.baseImage = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableAutomaticUpdates) {
      self.enableAutomaticUpdates = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workerPool) {
      self.workerPool = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .environmentVariables)
    {
      self.environmentVariables = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.sourceLocation, forKey: .sourceLocation)
    try container.encode(self.functionTarget, forKey: .functionTarget)
    try container.encode(self.imageUri, forKey: .imageUri)
    try container.encode(self.baseImage, forKey: .baseImage)
    try container.encode(self.enableAutomaticUpdates, forKey: .enableAutomaticUpdates)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.environmentVariables, forKey: .environmentVariables)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.BuildConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
