// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleLongrunning
import Logging

/// Cloud Run Build Control Plane API
///
/// @Snippet(path: "BuildsQuickstart")
public protocol Builds {
  /// Submits a build in a given project.
  ///
  /// @Snippet(path: "Builds_SubmitBuild")
  func submitBuild(request: SubmitBuildRequest) async throws -> GoogleCloudRunV2.SubmitBuildResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  >

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_WaitOperation")
  func waitOperation(request: WaitOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Submits a build in a given project.
  ///
  /// @Snippet(path: "Builds_SubmitBuild")
  func submitBuild(
    request: SubmitBuildRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.SubmitBuildResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Builds_WaitOperation")
  func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``Builds``.
  public class BuildsClient: Builds {
    let inner: any BuildsStub

    /// Creates a new `BuildsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any BuildsStub = try BuildsTransport(options)
      inner = BuildsRetry(inner, options: options)
      if let logger = options.logger {
        inner = BuildsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Builds.submitBuild`
    public func submitBuild(
      request: SubmitBuildRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.SubmitBuildResponse {
      try await self.inner.submitBuild(request: request, options: options)
    }

    /// See `Builds.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Builds.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `Builds.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `Builds.waitOperation`
    public func waitOperation(
      request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Builds {
  public func submitBuild(request: SubmitBuildRequest) async throws
    -> GoogleCloudRunV2.SubmitBuildResponse
  {
    try await self.submitBuild(request: request, options: .init())
  }

  public func submitBuild(
    request: SubmitBuildRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.SubmitBuildResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  > {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func waitOperation(request: WaitOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.waitOperation(request: request, options: .init())
  }

  public func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
