// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

public struct CreateInstanceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var parent: Swift.String = Swift.String()

  public var instance: Instance? = nil

  /// Required. The unique identifier for the Instance. It must begin with
  /// letter, and cannot end with hyphen; must contain fewer than 50 characters.
  /// The name of the instance becomes {parent}/instances/{instance_id}.
  public var instanceId: Swift.String = Swift.String()

  /// Optional. Indicates that the request should be validated and default values
  /// populated, without persisting the request or creating any resources.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateInstanceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateInstanceRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.CreateInstanceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
