// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// EnvVar represents an environment variable present in a Container.
public struct EnvVar: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the environment variable. Must not exceed 32768
  /// characters.
  public var name: Swift.String

  public var values: OneOf_Values?

  /// Initialize a new instance of `EnvVar`.
  public init(
    name: Swift.String = Swift.String(),
    values: OneOf_Values? = nil,
  ) {
    self.name = name
    self.values = values
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case value = "value"
    case valueSource = "valueSource"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)

    var values: OneOf_Values? = nil
    let valuesCheckAndSet = {
      if values != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'values'"))
      }
      values = $0
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
      try valuesCheckAndSet(.value(value))
    }
    if let valueSource = try container.decodeIfPresent(EnvVarSource?.self, forKey: .valueSource) {
      try valuesCheckAndSet(.valueSource(valueSource))
    }
    self.values = values
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)

    if let choice = self.values {
      switch choice {
      case .value(let value):
        try container.encode(value, forKey: .value)
      case .valueSource(let value):
        try container.encode(value, forKey: .valueSource)
      }
    }
  }

  public enum OneOf_Values: Codable, Equatable, Sendable {
    /// Literal value of the environment variable.
    /// Defaults to "", and the maximum length is 32768 bytes.
    /// Variable references are not supported in Cloud Run.
    case value(Swift.String)
    /// Source for the environment variable's value.
    indirect case valueSource(EnvVarSource?)
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.cloud.run.v2.EnvVar" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
