// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleWKT

/// Execution represents the configuration of a single execution. A execution an
/// immutable resource that references a container image which is run to
/// completion.
public struct Execution: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The unique name of this Execution.
  public var name: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the Execution. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. Email address of the authenticated creator.
  public var creator: Swift.String = Swift.String()

  /// Output only. A number that monotonically increases every time the user
  /// modifies the desired state.
  public var generation: Swift.Int64 = Swift.Int64()

  /// Output only. Unstructured key value map that can be used to organize and
  /// categorize objects. User-provided labels are shared with Google's billing
  /// system, so they can be used to filter, or break down billing charges by
  /// team, component, environment, state, etc. For more information, visit
  /// https://cloud.google.com/resource-manager/docs/creating-managing-labels or
  /// https://cloud.google.com/run/docs/configuring/labels
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Unstructured key value map that may
  /// be set by external tools to store and arbitrary metadata.
  /// They are not queryable and should be preserved
  /// when modifying objects.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. Represents time when the execution was acknowledged by the
  /// execution controller. It is not guaranteed to be set in happens-before
  /// order across separate operations.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. Represents time when the execution started to run.
  /// It is not guaranteed to be set in happens-before order across separate
  /// operations.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Output only. Represents time when the execution was completed. It is not
  /// guaranteed to be set in happens-before order across separate operations.
  public var completionTime: GoogleWKT.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. For a deleted resource, the deletion time. It is only
  /// populated as a response to a Delete request.
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Output only. For a deleted resource, the time after which it will be
  /// permamently deleted. It is only populated as a response to a Delete
  /// request.
  public var expireTime: GoogleWKT.Timestamp? = nil

  /// The least stable launch stage needed to create this resource, as defined by
  /// [Google Cloud Platform Launch
  /// Stages](https://cloud.google.com/terms/launch-stages). Cloud Run supports
  /// `ALPHA`, `BETA`, and `GA`.
  ///
  /// Note that this value might not be what was used
  /// as input. For example, if ALPHA was provided as input in the parent
  /// resource, but only BETA and GA-level features are were, this field will be
  /// BETA.
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Output only. The name of the parent Job.
  public var job: Swift.String = Swift.String()

  /// Output only. Specifies the maximum desired number of tasks the execution
  /// should run at any given time. Must be <= task_count. The actual number of
  /// tasks running in steady state will be less than this number when
  /// ((.spec.task_count - .status.successful) < .spec.parallelism), i.e. when
  /// the work left to do is less than max parallelism.
  public var parallelism: Swift.Int32 = Swift.Int32()

  /// Output only. Specifies the desired number of tasks the execution should
  /// run. Setting to 1 means that parallelism is limited to 1 and the success of
  /// that task signals the success of the execution.
  public var taskCount: Swift.Int32 = Swift.Int32()

  /// Output only. The template used to create tasks for this execution.
  public var template: TaskTemplate? = nil

  /// Output only. Indicates whether the resource's reconciliation is still in
  /// progress. See comments in `Job.reconciling` for additional information on
  /// reconciliation process in Cloud Run.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Output only. The Condition of this Execution, containing its readiness
  /// status, and detailed error information in case it did not reach the desired
  /// state.
  public var conditions: [Condition] = []

  /// Output only. The generation of this Execution. See comments in
  /// `reconciling` for additional information on reconciliation process in Cloud
  /// Run.
  public var observedGeneration: Swift.Int64 = Swift.Int64()

  /// Output only. The number of actively running tasks.
  public var runningCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of tasks which reached phase Succeeded.
  public var succeededCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of tasks which reached phase Failed.
  public var failedCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of tasks which reached phase Cancelled.
  public var cancelledCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of tasks which have retried at least once.
  public var retriedCount: Swift.Int32 = Swift.Int32()

  /// Output only. URI where logs for this execution can be found in Cloud
  /// Console.
  public var logUri: Swift.String = Swift.String()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. A system-generated fingerprint for this version of the
  /// resource. May be used to detect modification conflict during updates.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Execution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Execution().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let creator = CodingKeys(stringValue: "creator")
    static let generation = CodingKeys(stringValue: "generation")
    static let labels = CodingKeys(stringValue: "labels")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let completionTime = CodingKeys(stringValue: "completionTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let launchStage = CodingKeys(stringValue: "launchStage")
    static let job = CodingKeys(stringValue: "job")
    static let parallelism = CodingKeys(stringValue: "parallelism")
    static let taskCount = CodingKeys(stringValue: "taskCount")
    static let template = CodingKeys(stringValue: "template")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let conditions = CodingKeys(stringValue: "conditions")
    static let observedGeneration = CodingKeys(stringValue: "observedGeneration")
    static let runningCount = CodingKeys(stringValue: "runningCount")
    static let succeededCount = CodingKeys(stringValue: "succeededCount")
    static let failedCount = CodingKeys(stringValue: "failedCount")
    static let cancelledCount = CodingKeys(stringValue: "cancelledCount")
    static let retriedCount = CodingKeys(stringValue: "retriedCount")
    static let logUri = CodingKeys(stringValue: "logUri")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "creator",
      "generation",
      "labels",
      "annotations",
      "createTime",
      "startTime",
      "completionTime",
      "updateTime",
      "deleteTime",
      "expireTime",
      "launchStage",
      "job",
      "parallelism",
      "taskCount",
      "template",
      "reconciling",
      "conditions",
      "observedGeneration",
      "runningCount",
      "succeededCount",
      "failedCount",
      "cancelledCount",
      "retriedCount",
      "logUri",
      "satisfiesPzs",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .creator) {
      self.creator = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .generation) {
      self.generation = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.completionTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .completionTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    self.expireTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(GoogleApi.LaunchStage.self, forKey: .launchStage) {
      self.launchStage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .job) {
      self.job = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .parallelism) {
      self.parallelism = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .taskCount) {
      self.taskCount = value
    }
    self.template = try container.decodeIfPresent(TaskTemplate.self, forKey: .template)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent([Condition].self, forKey: .conditions) {
      self.conditions = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .observedGeneration) {
      self.observedGeneration = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .runningCount) {
      self.runningCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .succeededCount) {
      self.succeededCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .failedCount) {
      self.failedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .cancelledCount) {
      self.cancelledCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .retriedCount) {
      self.retriedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logUri) {
      self.logUri = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.creator, forKey: .creator)
    try container.encode(self.generation, forKey: .generation)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.completionTime, forKey: .completionTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.launchStage, forKey: .launchStage)
    try container.encode(self.job, forKey: .job)
    try container.encode(self.parallelism, forKey: .parallelism)
    try container.encode(self.taskCount, forKey: .taskCount)
    try container.encodeIfPresent(self.template, forKey: .template)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.conditions, forKey: .conditions)
    try container.encode(self.observedGeneration, forKey: .observedGeneration)
    try container.encode(self.runningCount, forKey: .runningCount)
    try container.encode(self.succeededCount, forKey: .succeededCount)
    try container.encode(self.failedCount, forKey: .failedCount)
    try container.encode(self.cancelledCount, forKey: .cancelledCount)
    try container.encode(self.retriedCount, forKey: .retriedCount)
    try container.encode(self.logUri, forKey: .logUri)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.Execution"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
