// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// Cloud Run Execution Control Plane API.
///
/// @Snippet(path: "ExecutionsQuickstart")
public protocol Executions {
  /// Gets information about an Execution.
  ///
  /// @Snippet(path: "Executions_GetExecution")
  func getExecution(request: GetExecutionRequest) async throws -> GoogleCloudRunV2.Execution

  /// Lists Executions from a Job. Results are sorted by creation time,
  /// descending.
  ///
  /// @Snippet(path: "Executions_ListExecutions")
  func listExecutions(request: ListExecutionsRequest) async throws
    -> GoogleCloudRunV2.ListExecutionsResponse

  /// Lists Executions from a Job. Results are sorted by creation time,
  /// descending.
  func listExecutions(
    byItem: ListExecutionsRequest
  ) throws -> any AsyncSequence<Execution, Swift.Error>

  /// Deletes an Execution.
  ///
  /// @Snippet(path: "Executions_DeleteExecution")
  func deleteExecution(request: DeleteExecutionRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes an Execution.
  func deleteExecution(withPolling: DeleteExecutionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Execution>

  /// Cancels an Execution.
  ///
  /// @Snippet(path: "Executions_CancelExecution")
  func cancelExecution(request: CancelExecutionRequest) async throws -> GoogleLongrunning.Operation

  /// Cancels an Execution.
  func cancelExecution(withPolling: CancelExecutionRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Execution>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_WaitOperation")
  func waitOperation(request: WaitOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Gets information about an Execution.
  ///
  /// @Snippet(path: "Executions_GetExecution")
  func getExecution(
    request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Execution

  /// Lists Executions from a Job. Results are sorted by creation time,
  /// descending.
  ///
  /// @Snippet(path: "Executions_ListExecutions")
  func listExecutions(
    request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListExecutionsResponse

  /// Lists Executions from a Job. Results are sorted by creation time,
  /// descending.
  func listExecutions(
    byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Execution, Swift.Error>

  /// Deletes an Execution.
  ///
  /// @Snippet(path: "Executions_DeleteExecution")
  func deleteExecution(
    request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes an Execution.
  func deleteExecution(
    withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution>

  /// Cancels an Execution.
  ///
  /// @Snippet(path: "Executions_CancelExecution")
  func cancelExecution(
    request: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Cancels an Execution.
  func cancelExecution(
    withPolling: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Executions_WaitOperation")
  func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``Executions``.
  public class ExecutionsClient: Executions {
    let inner: any ExecutionsStub

    /// Creates a new `ExecutionsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any ExecutionsStub = try ExecutionsTransport(options)
      inner = ExecutionsRetry(inner, options: options)
      if let logger = options.logger {
        inner = ExecutionsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Executions.getExecution`
    public func getExecution(
      request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.Execution {
      try await self.inner.getExecution(request: request, options: options)
    }

    /// See `Executions.listExecutions`
    public func listExecutions(
      request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.ListExecutionsResponse {
      try await self.inner.listExecutions(request: request, options: options)
    }

    /// Lists Executions from a Job. Results are sorted by creation time,
    /// descending.
    public func listExecutions(
      byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Execution, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListExecutionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listExecutions(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Executions.deleteExecution`
    public func deleteExecution(
      request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteExecution(request: request, options: options)
    }

    /// Deletes an Execution.
    public func deleteExecution(
      withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Execution(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteExecution(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `Executions.cancelExecution`
    public func cancelExecution(
      request: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.cancelExecution(request: request, options: options)
    }

    /// Cancels an Execution.
    public func cancelExecution(
      withPolling: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Execution(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.cancelExecution(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `Executions.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Executions.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `Executions.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `Executions.waitOperation`
    public func waitOperation(
      request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Executions {
  public func getExecution(request: GetExecutionRequest) async throws -> GoogleCloudRunV2.Execution
  {
    try await self.getExecution(request: request, options: .init())
  }

  public func getExecution(
    request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Execution {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listExecutions(request: ListExecutionsRequest) async throws
    -> GoogleCloudRunV2.ListExecutionsResponse
  {
    try await self.listExecutions(request: request, options: .init())
  }

  public func listExecutions(
    request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListExecutionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listExecutions(
    byItem: ListExecutionsRequest
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    try self.listExecutions(byItem: byItem, options: .init())
  }

  public func listExecutions(
    byItem: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Execution, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListExecutionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func deleteExecution(request: DeleteExecutionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteExecution(request: request, options: .init())
  }

  public func deleteExecution(
    request: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteExecution(withPolling: DeleteExecutionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Execution>
  {
    try await self.deleteExecution(withPolling: withPolling, options: .init())
  }

  public func deleteExecution(
    withPolling: DeleteExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func cancelExecution(request: CancelExecutionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.cancelExecution(request: request, options: .init())
  }

  public func cancelExecution(
    request: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelExecution(withPolling: CancelExecutionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Execution>
  {
    try await self.cancelExecution(withPolling: withPolling, options: .init())
  }

  public func cancelExecution(
    withPolling: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Execution> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Execution>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func waitOperation(request: WaitOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.waitOperation(request: request, options: .init())
  }

  public func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
