// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a volume backed by a Cloud Storage bucket using Cloud Storage
/// FUSE.
public struct GCSVolumeSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Cloud Storage Bucket name.
  public var bucket: Swift.String

  /// If true, the volume will be mounted as read only for all mounts.
  public var readOnly: Swift.Bool

  /// A list of additional flags to pass to the gcsfuse CLI.
  /// Options should be specified without the leading "--".
  public var mountOptions: [Swift.String]

  /// Initialize a new instance of `GCSVolumeSource`.
  public init(
    bucket: Swift.String = Swift.String(),
    readOnly: Swift.Bool = Swift.Bool(),
    mountOptions: [Swift.String] = [],
  ) {
    self.bucket = bucket
    self.readOnly = readOnly
    self.mountOptions = mountOptions
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.GCSVolumeSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
