// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// GRPCAction describes an action involving a GRPC port.
public struct GRPCAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Port number of the gRPC service. Number must be in the range 1 to
  /// 65535. If not specified, defaults to the exposed port of the container,
  /// which is the value of container.ports[0].containerPort.
  public var port: Swift.Int32

  /// Optional. Service is the name of the service to place in the gRPC
  /// HealthCheckRequest (see
  /// https://github.com/grpc/grpc/blob/master/doc/health-checking.md ). If this
  /// is not specified, the default behavior is defined by gRPC.
  public var service: Swift.String

  /// Initialize a new instance of `GRPCAction`.
  public init(
    port: Swift.Int32 = Swift.Int32(),
    service: Swift.String = Swift.String(),
  ) {
    self.port = port
    self.service = service
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.GRPCAction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
