// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// HTTPGetAction describes an action based on HTTP Get requests.
public struct HTTPGetAction: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Path to access on the HTTP server. Defaults to '/'.
  public var path: Swift.String = Swift.String()

  /// Optional. Custom headers to set in the request. HTTP allows repeated
  /// headers.
  public var httpHeaders: [HTTPHeader] = []

  /// Optional. Port number to access on the container. Must be in the range 1 to
  /// 65535. If not specified, defaults to the exposed port of the container,
  /// which is the value of container.ports[0].containerPort.
  public var port: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HTTPGetAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HTTPGetAction().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let path = CodingKeys(stringValue: "path")
    static let httpHeaders = CodingKeys(stringValue: "httpHeaders")
    static let port = CodingKeys(stringValue: "port")

    static let _knownKeys: Set<Swift.String> = [
      "path",
      "httpHeaders",
      "port",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .path) {
      self.path = value
    }
    if let value = try container.decodeIfPresent([HTTPHeader].self, forKey: .httpHeaders) {
      self.httpHeaders = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.httpHeaders, forKey: .httpHeaders)
    try container.encode(self.port, forKey: .port)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.HTTPGetAction"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
