// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleWKT

/// A Cloud Run Instance represents a single group of containers running in a
/// region.
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The fully qualified name of this Instance. In CreateInstanceRequest, this
  /// field is ignored, and instead composed from CreateInstanceRequest.parent
  /// and CreateInstanceRequest.instance_id.
  ///
  /// Format:
  /// projects/{project}/locations/{location}/instances/{instance_id}
  public var name: Swift.String = Swift.String()

  /// User-provided description of the Instance. This field currently has a
  /// 512-character limit.
  public var description: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the trigger. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. A number that monotonically increases every time the user
  /// modifies the desired state.
  /// Please note that unlike v1, this is an int64 value. As with most Google
  /// APIs, its JSON representation will be a `string` instead of an `integer`.
  public var generation: Swift.Int64 = Swift.Int64()

  public var labels: [Swift.String: Swift.String] = [:]

  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The creation time.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Output only. The deletion time.
  public var deleteTime: GoogleWKT.Timestamp? = nil

  /// Output only. For a deleted resource, the time after which it will be
  /// permamently deleted.
  public var expireTime: GoogleWKT.Timestamp? = nil

  /// Output only. Email address of the authenticated creator.
  public var creator: Swift.String = Swift.String()

  /// Output only. Email address of the last authenticated modifier.
  public var lastModifier: Swift.String = Swift.String()

  /// Arbitrary identifier for the API client.
  public var client: Swift.String = Swift.String()

  /// Arbitrary version identifier for the API client.
  public var clientVersion: Swift.String = Swift.String()

  /// The launch stage as defined by [Google Cloud Platform
  ///  Launch Stages](https://cloud.google.com/terms/launch-stages).
  ///  Cloud Run supports `ALPHA`, `BETA`, and `GA`. If no value is specified, GA
  ///  is assumed.
  ///  Set the launch stage to a preview stage on input to allow use of preview
  ///  features in that stage. On read (or output), describes whether the
  ///  resource uses preview features.
  /// <p>
  ///  For example, if ALPHA is provided as input, but only BETA and GA-level
  ///  features are used, this field will be BETA on output.
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Settings for the Binary Authorization feature.
  public var binaryAuthorization: BinaryAuthorization? = nil

  /// Optional. VPC Access configuration to use for this Revision. For more
  /// information, visit
  /// https://cloud.google.com/run/docs/configuring/connecting-vpc.
  public var vpcAccess: VpcAccess? = nil

  public var serviceAccount: Swift.String = Swift.String()

  /// Required. Holds the single container that defines the unit of execution for
  /// this Instance.
  public var containers: [Container] = []

  /// A list of Volumes to make available to containers.
  public var volumes: [Volume] = []

  /// A reference to a customer managed encryption key (CMEK) to use to encrypt
  /// this container image. For more information, go to
  /// https://cloud.google.com/run/docs/securing/using-cmek
  public var encryptionKey: Swift.String = Swift.String()

  /// The action to take if the encryption key is revoked.
  public var encryptionKeyRevocationAction: EncryptionKeyRevocationAction =
    EncryptionKeyRevocationAction()

  /// If encryption_key_revocation_action is SHUTDOWN, the duration before
  /// shutting down all instances. The minimum increment is 1 hour.
  public var encryptionKeyShutdownDuration: GoogleWKT.Duration? = nil

  /// Optional. The node selector for the instance.
  public var nodeSelector: NodeSelector? = nil

  /// Optional. True if GPU zonal redundancy is disabled on this instance.
  public var gpuZonalRedundancyDisabled: Swift.Bool? = nil

  /// Optional. Provides the ingress settings for this Instance. On output,
  /// returns the currently observed ingress settings, or
  /// INGRESS_TRAFFIC_UNSPECIFIED if no revision is active.
  public var ingress: IngressTraffic = IngressTraffic()

  /// Optional. Disables IAM permission check for run.routes.invoke for callers
  /// of this Instance. For more information, visit
  /// https://cloud.google.com/run/docs/securing/managing-access#invoker_check.
  public var invokerIamDisabled: Swift.Bool = Swift.Bool()

  /// Optional. IAP settings on the Instance.
  public var iapEnabled: Swift.Bool = Swift.Bool()

  /// Output only. The generation of this Instance currently serving traffic. See
  /// comments in `reconciling` for additional information on reconciliation
  /// process in Cloud Run. Please note that unlike v1, this is an int64 value.
  /// As with most Google APIs, its JSON representation will be a `string`
  /// instead of an `integer`.
  public var observedGeneration: Swift.Int64 = Swift.Int64()

  /// Output only. The Google Console URI to obtain logs for the Instance.
  public var logUri: Swift.String = Swift.String()

  /// Output only. The Condition of this Instance, containing its readiness
  /// status, and detailed error information in case it did not reach a serving
  /// state. See comments in `reconciling` for additional information on
  /// reconciliation process in Cloud Run.
  public var terminalCondition: Condition? = nil

  /// Output only. The Conditions of all other associated sub-resources. They
  /// contain additional diagnostics information in case the Instance does not
  /// reach its Serving state. See comments in `reconciling` for additional
  /// information on reconciliation process in Cloud Run.
  public var conditions: [Condition] = []

  /// Output only. Status information for each of the specified containers. The
  /// status includes the resolved digest for specified images.
  public var containerStatuses: [ContainerStatus] = []

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. All URLs serving traffic for this Instance.
  public var urls: [Swift.String] = []

  /// Output only. Returns true if the Instance is currently being acted upon by
  /// the system to bring it into the desired state.
  ///
  /// When a new Instance is created, or an existing one is updated, Cloud Run
  /// will asynchronously perform all necessary steps to bring the Instance to
  /// the desired serving state. This process is called reconciliation. While
  /// reconciliation is in process, `observed_generation` will have a transient
  /// value that might mismatch the intended state.
  ///  Once reconciliation is over (and this field is false), there are two
  /// possible outcomes: reconciliation succeeded and the serving state matches
  /// the Instance, or there was an error, and reconciliation failed. This state
  /// can be found in `terminal_condition.state`.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. A system-generated fingerprint for this version of the
  /// resource. May be used to detect modification conflict during updates.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let uid = CodingKeys(stringValue: "uid")
    static let generation = CodingKeys(stringValue: "generation")
    static let labels = CodingKeys(stringValue: "labels")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let deleteTime = CodingKeys(stringValue: "deleteTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let lastModifier = CodingKeys(stringValue: "lastModifier")
    static let client = CodingKeys(stringValue: "client")
    static let clientVersion = CodingKeys(stringValue: "clientVersion")
    static let launchStage = CodingKeys(stringValue: "launchStage")
    static let binaryAuthorization = CodingKeys(stringValue: "binaryAuthorization")
    static let vpcAccess = CodingKeys(stringValue: "vpcAccess")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let containers = CodingKeys(stringValue: "containers")
    static let volumes = CodingKeys(stringValue: "volumes")
    static let encryptionKey = CodingKeys(stringValue: "encryptionKey")
    static let encryptionKeyRevocationAction = CodingKeys(
      stringValue: "encryptionKeyRevocationAction")
    static let encryptionKeyShutdownDuration = CodingKeys(
      stringValue: "encryptionKeyShutdownDuration")
    static let nodeSelector = CodingKeys(stringValue: "nodeSelector")
    static let gpuZonalRedundancyDisabled = CodingKeys(stringValue: "gpuZonalRedundancyDisabled")
    static let ingress = CodingKeys(stringValue: "ingress")
    static let invokerIamDisabled = CodingKeys(stringValue: "invokerIamDisabled")
    static let iapEnabled = CodingKeys(stringValue: "iapEnabled")
    static let observedGeneration = CodingKeys(stringValue: "observedGeneration")
    static let logUri = CodingKeys(stringValue: "logUri")
    static let terminalCondition = CodingKeys(stringValue: "terminalCondition")
    static let conditions = CodingKeys(stringValue: "conditions")
    static let containerStatuses = CodingKeys(stringValue: "containerStatuses")
    static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
    static let urls = CodingKeys(stringValue: "urls")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "uid",
      "generation",
      "labels",
      "annotations",
      "createTime",
      "updateTime",
      "deleteTime",
      "expireTime",
      "creator",
      "lastModifier",
      "client",
      "clientVersion",
      "launchStage",
      "binaryAuthorization",
      "vpcAccess",
      "serviceAccount",
      "containers",
      "volumes",
      "encryptionKey",
      "encryptionKeyRevocationAction",
      "encryptionKeyShutdownDuration",
      "nodeSelector",
      "gpuZonalRedundancyDisabled",
      "ingress",
      "invokerIamDisabled",
      "iapEnabled",
      "observedGeneration",
      "logUri",
      "terminalCondition",
      "conditions",
      "containerStatuses",
      "satisfiesPzs",
      "urls",
      "reconciling",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .generation) {
      self.generation = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .deleteTime)
    self.expireTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .creator) {
      self.creator = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lastModifier) {
      self.lastModifier = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .client) {
      self.client = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientVersion) {
      self.clientVersion = value
    }
    if let value = try container.decodeIfPresent(GoogleApi.LaunchStage.self, forKey: .launchStage) {
      self.launchStage = value
    }
    self.binaryAuthorization = try container.decodeIfPresent(
      BinaryAuthorization.self, forKey: .binaryAuthorization)
    self.vpcAccess = try container.decodeIfPresent(VpcAccess.self, forKey: .vpcAccess)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent([Container].self, forKey: .containers) {
      self.containers = value
    }
    if let value = try container.decodeIfPresent([Volume].self, forKey: .volumes) {
      self.volumes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .encryptionKey) {
      self.encryptionKey = value
    }
    if let value = try container.decodeIfPresent(
      EncryptionKeyRevocationAction.self, forKey: .encryptionKeyRevocationAction)
    {
      self.encryptionKeyRevocationAction = value
    }
    self.encryptionKeyShutdownDuration = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .encryptionKeyShutdownDuration)
    self.nodeSelector = try container.decodeIfPresent(NodeSelector.self, forKey: .nodeSelector)
    self.gpuZonalRedundancyDisabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .gpuZonalRedundancyDisabled)
    if let value = try container.decodeIfPresent(IngressTraffic.self, forKey: .ingress) {
      self.ingress = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .invokerIamDisabled) {
      self.invokerIamDisabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .iapEnabled) {
      self.iapEnabled = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .observedGeneration) {
      self.observedGeneration = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .logUri) {
      self.logUri = value
    }
    self.terminalCondition = try container.decodeIfPresent(
      Condition.self, forKey: .terminalCondition)
    if let value = try container.decodeIfPresent([Condition].self, forKey: .conditions) {
      self.conditions = value
    }
    if let value = try container.decodeIfPresent([ContainerStatus].self, forKey: .containerStatuses)
    {
      self.containerStatuses = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs) {
      self.satisfiesPzs = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .urls) {
      self.urls = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.generation, forKey: .generation)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.deleteTime, forKey: .deleteTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.creator, forKey: .creator)
    try container.encode(self.lastModifier, forKey: .lastModifier)
    try container.encode(self.client, forKey: .client)
    try container.encode(self.clientVersion, forKey: .clientVersion)
    try container.encode(self.launchStage, forKey: .launchStage)
    try container.encodeIfPresent(self.binaryAuthorization, forKey: .binaryAuthorization)
    try container.encodeIfPresent(self.vpcAccess, forKey: .vpcAccess)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.containers, forKey: .containers)
    try container.encode(self.volumes, forKey: .volumes)
    try container.encode(self.encryptionKey, forKey: .encryptionKey)
    try container.encode(self.encryptionKeyRevocationAction, forKey: .encryptionKeyRevocationAction)
    try container.encodeIfPresent(
      self.encryptionKeyShutdownDuration, forKey: .encryptionKeyShutdownDuration)
    try container.encodeIfPresent(self.nodeSelector, forKey: .nodeSelector)
    try container.encodeIfPresent(
      self.gpuZonalRedundancyDisabled, forKey: .gpuZonalRedundancyDisabled)
    try container.encode(self.ingress, forKey: .ingress)
    try container.encode(self.invokerIamDisabled, forKey: .invokerIamDisabled)
    try container.encode(self.iapEnabled, forKey: .iapEnabled)
    try container.encode(self.observedGeneration, forKey: .observedGeneration)
    try container.encode(self.logUri, forKey: .logUri)
    try container.encodeIfPresent(self.terminalCondition, forKey: .terminalCondition)
    try container.encode(self.conditions, forKey: .conditions)
    try container.encode(self.containerStatuses, forKey: .containerStatuses)
    try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
    try container.encode(self.urls, forKey: .urls)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.Instance"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
