// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Cloud Run Instance represents a single group of containers running in a
/// region.
public struct Instance: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The fully qualified name of this Instance. In CreateInstanceRequest, this
  /// field is ignored, and instead composed from CreateInstanceRequest.parent
  /// and CreateInstanceRequest.instance_id.
  ///
  /// Format:
  /// projects/{project}/locations/{location}/instances/{instance_id}
  public var name: Swift.String = Swift.String()

  /// User-provided description of the Instance. This field currently has a
  /// 512-character limit.
  public var description: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the trigger. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. A number that monotonically increases every time the user
  /// modifies the desired state.
  /// Please note that unlike v1, this is an int64 value. As with most Google
  /// APIs, its JSON representation will be a `string` instead of an `integer`.
  public var generation: Swift.Int64 = Swift.Int64()

  public var labels: [Swift.String: Swift.String] = [:]

  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The creation time.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The deletion time.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. For a deleted resource, the time after which it will be
  /// permamently deleted.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Email address of the authenticated creator.
  public var creator: Swift.String = Swift.String()

  /// Output only. Email address of the last authenticated modifier.
  public var lastModifier: Swift.String = Swift.String()

  /// Arbitrary identifier for the API client.
  public var client: Swift.String = Swift.String()

  /// Arbitrary version identifier for the API client.
  public var clientVersion: Swift.String = Swift.String()

  /// The launch stage as defined by [Google Cloud Platform
  ///  Launch Stages](https://cloud.google.com/terms/launch-stages).
  ///  Cloud Run supports `ALPHA`, `BETA`, and `GA`. If no value is specified, GA
  ///  is assumed.
  ///  Set the launch stage to a preview stage on input to allow use of preview
  ///  features in that stage. On read (or output), describes whether the
  ///  resource uses preview features.
  /// <p>
  ///  For example, if ALPHA is provided as input, but only BETA and GA-level
  ///  features are used, this field will be BETA on output.
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Settings for the Binary Authorization feature.
  public var binaryAuthorization: BinaryAuthorization? = nil

  /// Optional. VPC Access configuration to use for this Revision. For more
  /// information, visit
  /// https://cloud.google.com/run/docs/configuring/connecting-vpc.
  public var vpcAccess: VpcAccess? = nil

  public var serviceAccount: Swift.String = Swift.String()

  /// Required. Holds the single container that defines the unit of execution for
  /// this Instance.
  public var containers: [Container] = []

  /// A list of Volumes to make available to containers.
  public var volumes: [Volume] = []

  /// A reference to a customer managed encryption key (CMEK) to use to encrypt
  /// this container image. For more information, go to
  /// https://cloud.google.com/run/docs/securing/using-cmek
  public var encryptionKey: Swift.String = Swift.String()

  /// The action to take if the encryption key is revoked.
  public var encryptionKeyRevocationAction: EncryptionKeyRevocationAction =
    EncryptionKeyRevocationAction()

  /// If encryption_key_revocation_action is SHUTDOWN, the duration before
  /// shutting down all instances. The minimum increment is 1 hour.
  public var encryptionKeyShutdownDuration: GoogleCloudWKT.Duration? = nil

  /// Optional. The node selector for the instance.
  public var nodeSelector: NodeSelector? = nil

  /// Optional. True if GPU zonal redundancy is disabled on this instance.
  public var gpuZonalRedundancyDisabled: Swift.Bool? = nil

  /// Optional. Provides the ingress settings for this Instance. On output,
  /// returns the currently observed ingress settings, or
  /// INGRESS_TRAFFIC_UNSPECIFIED if no revision is active.
  public var ingress: IngressTraffic = IngressTraffic()

  /// Optional. Disables IAM permission check for run.routes.invoke for callers
  /// of this Instance. For more information, visit
  /// https://cloud.google.com/run/docs/securing/managing-access#invoker_check.
  public var invokerIamDisabled: Swift.Bool = Swift.Bool()

  /// Optional. IAP settings on the Instance.
  public var iapEnabled: Swift.Bool = Swift.Bool()

  /// Output only. The generation of this Instance currently serving traffic. See
  /// comments in `reconciling` for additional information on reconciliation
  /// process in Cloud Run. Please note that unlike v1, this is an int64 value.
  /// As with most Google APIs, its JSON representation will be a `string`
  /// instead of an `integer`.
  public var observedGeneration: Swift.Int64 = Swift.Int64()

  /// Output only. The Google Console URI to obtain logs for the Instance.
  public var logUri: Swift.String = Swift.String()

  /// Output only. The Condition of this Instance, containing its readiness
  /// status, and detailed error information in case it did not reach a serving
  /// state. See comments in `reconciling` for additional information on
  /// reconciliation process in Cloud Run.
  public var terminalCondition: Condition? = nil

  /// Output only. The Conditions of all other associated sub-resources. They
  /// contain additional diagnostics information in case the Instance does not
  /// reach its Serving state. See comments in `reconciling` for additional
  /// information on reconciliation process in Cloud Run.
  public var conditions: [Condition] = []

  /// Output only. Status information for each of the specified containers. The
  /// status includes the resolved digest for specified images.
  public var containerStatuses: [ContainerStatus] = []

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. All URLs serving traffic for this Instance.
  public var urls: [Swift.String] = []

  /// Output only. Returns true if the Instance is currently being acted upon by
  /// the system to bring it into the desired state.
  ///
  /// When a new Instance is created, or an existing one is updated, Cloud Run
  /// will asynchronously perform all necessary steps to bring the Instance to
  /// the desired serving state. This process is called reconciliation. While
  /// reconciliation is in process, `observed_generation` will have a transient
  /// value that might mismatch the intended state.
  ///  Once reconciliation is over (and this field is false), there are two
  /// possible outcomes: reconciliation succeeded and the serving state matches
  /// the Instance, or there was an error, and reconciliation failed. This state
  /// can be found in `terminal_condition.state`.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. A system-generated fingerprint for this version of the
  /// resource. May be used to detect modification conflict during updates.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.Instance"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
