// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message containing a list of Instances.
public struct ListInstancesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The resulting list of Instances.
  public var instances: [Instance]

  /// A token indicating there are more items than page_size. Use it in the next
  /// ListInstances request to continue.
  public var nextPageToken: Swift.String

  /// Initialize a new instance of `ListInstancesResponse`.
  public init(
    instances: [Instance] = [],
    nextPageToken: Swift.String = Swift.String(),
  ) {
    self.instances = instances
    self.nextPageToken = nextPageToken
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.ListInstancesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [Instance] {
    return self.instances
  }
}
