// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for retrieving a list of Revisions.
public struct ListRevisionsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The Service from which the Revisions should be listed.
  /// To list all Revisions across Services, use "-" instead of Service name.
  /// Format:
  /// projects/{project}/locations/{location}/services/{service}
  public var parent: Swift.String = Swift.String()

  /// Maximum number of revisions to return in this call.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token received from a previous call to ListRevisions.
  /// All other parameters must match.
  public var pageToken: Swift.String = Swift.String()

  /// If true, returns deleted (but unexpired) resources along with active ones.
  public var showDeleted: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ListRevisionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListRevisionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.ListRevisionsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
