// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Probe describes a health check to be performed against a container to
/// determine whether it is alive or ready to receive traffic.
public struct Probe: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Number of seconds after the container has started before the
  /// probe is initiated. Defaults to 0 seconds. Minimum value is 0. Maximum
  /// value for liveness probe is 3600. Maximum value for startup probe is 240.
  public var initialDelaySeconds: Swift.Int32 = Swift.Int32()

  /// Optional. Number of seconds after which the probe times out.
  /// Defaults to 1 second. Minimum value is 1. Maximum value is 3600.
  /// Must be smaller than period_seconds.
  public var timeoutSeconds: Swift.Int32 = Swift.Int32()

  /// Optional. How often (in seconds) to perform the probe.
  /// Default to 10 seconds. Minimum value is 1. Maximum value for liveness probe
  /// is 3600. Maximum value for startup probe is 240.
  /// Must be greater or equal than timeout_seconds.
  public var periodSeconds: Swift.Int32 = Swift.Int32()

  /// Optional. Minimum consecutive failures for the probe to be considered
  /// failed after having succeeded. Defaults to 3. Minimum value is 1.
  public var failureThreshold: Swift.Int32 = Swift.Int32()

  public var probeType: OneOf_ProbeType? = nil

  /// Initialize a new instance of `Probe`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Probe().with { $0.initialDelaySeconds = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case initialDelaySeconds = "initialDelaySeconds"
    case timeoutSeconds = "timeoutSeconds"
    case periodSeconds = "periodSeconds"
    case failureThreshold = "failureThreshold"
    case httpGet = "httpGet"
    case tcpSocket = "tcpSocket"
    case grpc = "grpc"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.initialDelaySeconds = try container.decode(Swift.Int32.self, forKey: .initialDelaySeconds)
    self.timeoutSeconds = try container.decode(Swift.Int32.self, forKey: .timeoutSeconds)
    self.periodSeconds = try container.decode(Swift.Int32.self, forKey: .periodSeconds)
    self.failureThreshold = try container.decode(Swift.Int32.self, forKey: .failureThreshold)

    var probeType: OneOf_ProbeType? = nil
    let probeTypeCheckAndSet = {
      if probeType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'probeType'"))
      }
      probeType = $0
    }
    if let httpGet = try container.decodeIfPresent(HTTPGetAction?.self, forKey: .httpGet) {
      try probeTypeCheckAndSet(.httpGet(httpGet))
    }
    if let tcpSocket = try container.decodeIfPresent(TCPSocketAction?.self, forKey: .tcpSocket) {
      try probeTypeCheckAndSet(.tcpSocket(tcpSocket))
    }
    if let grpc = try container.decodeIfPresent(GRPCAction?.self, forKey: .grpc) {
      try probeTypeCheckAndSet(.grpc(grpc))
    }
    self.probeType = probeType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.initialDelaySeconds, forKey: .initialDelaySeconds)
    try container.encode(self.timeoutSeconds, forKey: .timeoutSeconds)
    try container.encode(self.periodSeconds, forKey: .periodSeconds)
    try container.encode(self.failureThreshold, forKey: .failureThreshold)

    if let choice = self.probeType {
      switch choice {
      case .httpGet(let value):
        try container.encode(value, forKey: .httpGet)
      case .tcpSocket(let value):
        try container.encode(value, forKey: .tcpSocket)
      case .grpc(let value):
        try container.encode(value, forKey: .grpc)
      }
    }
  }

  public enum OneOf_ProbeType: Codable, Equatable, Sendable {
    /// Optional. HTTPGet specifies the http request to perform.
    /// Exactly one of httpGet, tcpSocket, or grpc must be specified.
    indirect case httpGet(HTTPGetAction?)
    /// Optional. TCPSocket specifies an action involving a TCP port.
    /// Exactly one of httpGet, tcpSocket, or grpc must be specified.
    indirect case tcpSocket(TCPSocketAction?)
    /// Optional. GRPC specifies an action involving a gRPC port.
    /// Exactly one of httpGet, tcpSocket, or grpc must be specified.
    indirect case grpc(GRPCAction?)
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.cloud.run.v2.Probe" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
