// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Settings for revision-level scaling settings.
public struct RevisionScaling: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Minimum number of serving instances that this resource should
  /// have.
  public var minInstanceCount: Swift.Int32 = Swift.Int32()

  /// Optional. Maximum number of serving instances that this resource should
  /// have. When unspecified, the field is set to the server default value of
  /// 100. For more information see
  /// https://cloud.google.com/run/docs/configuring/max-instances
  public var maxInstanceCount: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RevisionScaling`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RevisionScaling().with { $0.minInstanceCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let minInstanceCount = CodingKeys(stringValue: "minInstanceCount")
    static let maxInstanceCount = CodingKeys(stringValue: "maxInstanceCount")

    static let _knownKeys: Set<Swift.String> = [
      "minInstanceCount",
      "maxInstanceCount",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minInstanceCount) {
      self.minInstanceCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxInstanceCount) {
      self.maxInstanceCount = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.minInstanceCount, forKey: .minInstanceCount)
    try container.encode(self.maxInstanceCount, forKey: .maxInstanceCount)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.RevisionScaling"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
