// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleLongrunning
import Logging

/// Cloud Run Revision Control Plane API.
///
/// @Snippet(path: "RevisionsQuickstart")
public protocol Revisions {
  /// Gets information about a Revision.
  ///
  /// @Snippet(path: "Revisions_GetRevision")
  func getRevision(request: GetRevisionRequest) async throws -> GoogleCloudRunV2.Revision

  /// Lists Revisions from a given Service, or from a given location.  Results
  /// are sorted by creation time, descending.
  ///
  /// @Snippet(path: "Revisions_ListRevisions")
  func listRevisions(request: ListRevisionsRequest) async throws
    -> GoogleCloudRunV2.ListRevisionsResponse

  /// Lists Revisions from a given Service, or from a given location.  Results
  /// are sorted by creation time, descending.
  func listRevisions(byItem: ListRevisionsRequest) throws -> any AsyncSequence<Revision, Error>

  /// Deletes a Revision.
  ///
  /// @Snippet(path: "Revisions_DeleteRevision")
  func deleteRevision(request: DeleteRevisionRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  >

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_WaitOperation")
  func waitOperation(request: WaitOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Gets information about a Revision.
  ///
  /// @Snippet(path: "Revisions_GetRevision")
  func getRevision(
    request: GetRevisionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Revision

  /// Lists Revisions from a given Service, or from a given location.  Results
  /// are sorted by creation time, descending.
  ///
  /// @Snippet(path: "Revisions_ListRevisions")
  func listRevisions(
    request: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListRevisionsResponse

  /// Lists Revisions from a given Service, or from a given location.  Results
  /// are sorted by creation time, descending.
  func listRevisions(
    byItem: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Revision, Error>

  /// Deletes a Revision.
  ///
  /// @Snippet(path: "Revisions_DeleteRevision")
  func deleteRevision(
    request: DeleteRevisionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Revisions_WaitOperation")
  func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``Revisions``.
  public class RevisionsClient: Revisions {
    let inner: any RevisionsStub

    /// Creates a new `RevisionsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any RevisionsStub = try RevisionsTransport(options)
      inner = RevisionsRetry(inner, options: options)
      if let logger = options.logger {
        inner = RevisionsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Revisions.getRevision`
    public func getRevision(
      request: GetRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.Revision {
      try await self.inner.getRevision(request: request, options: options)
    }

    /// See `Revisions.listRevisions`
    public func listRevisions(
      request: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.ListRevisionsResponse {
      try await self.inner.listRevisions(request: request, options: options)
    }

    /// Lists Revisions from a given Service, or from a given location.  Results
    /// are sorted by creation time, descending.
    public func listRevisions(
      byItem: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Revision, Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListRevisionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listRevisions(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Revisions.deleteRevision`
    public func deleteRevision(
      request: DeleteRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteRevision(request: request, options: options)
    }

    /// See `Revisions.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Revisions.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `Revisions.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `Revisions.waitOperation`
    public func waitOperation(
      request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Revisions {
  public func getRevision(request: GetRevisionRequest) async throws -> GoogleCloudRunV2.Revision {
    try await self.getRevision(request: request, options: .init())
  }

  public func getRevision(
    request: GetRevisionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Revision {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRevisions(request: ListRevisionsRequest) async throws
    -> GoogleCloudRunV2.ListRevisionsResponse
  {
    try await self.listRevisions(request: request, options: .init())
  }

  public func listRevisions(
    request: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListRevisionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRevisions(byItem: ListRevisionsRequest) throws -> any AsyncSequence<
    Revision, Error
  > {
    try self.listRevisions(byItem: byItem, options: .init())
  }

  public func listRevisions(
    byItem: ListRevisionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Revision, Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListRevisionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func deleteRevision(request: DeleteRevisionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteRevision(request: request, options: .init())
  }

  public func deleteRevision(
    request: DeleteRevisionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  > {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func waitOperation(request: WaitOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.waitOperation(request: request, options: .init())
  }

  public func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
