// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message to create a new Execution of a Job.
public struct RunJobRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The full name of the Job.
  /// Format: projects/{project}/locations/{location}/jobs/{job}, where {project}
  /// can be project id or number.
  public var name: Swift.String = Swift.String()

  /// Indicates that the request should be validated without actually
  /// deleting any resources.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// A system-generated fingerprint for this version of the
  /// resource. May be used to detect modification conflict during updates.
  public var etag: Swift.String = Swift.String()

  /// Overrides specification for a given execution of a job. If provided,
  /// overrides will be applied to update the execution or task spec.
  public var overrides: RunJobRequest.Overrides? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RunJobRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RunJobRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")
    static let etag = CodingKeys(stringValue: "etag")
    static let overrides = CodingKeys(stringValue: "overrides")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "validateOnly",
      "etag",
      "overrides",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.overrides = try container.decodeIfPresent(RunJobRequest.Overrides.self, forKey: .overrides)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(self.overrides, forKey: .overrides)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// RunJob Overrides that contains Execution fields to be overridden.
  public struct Overrides: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Per container override specification.
    public var containerOverrides: [RunJobRequest.Overrides.ContainerOverride] = []

    /// Optional. The desired number of tasks the execution should run. Will
    /// replace existing task_count value.
    public var taskCount: Swift.Int32 = Swift.Int32()

    /// Duration in seconds the task may be active before the system will
    /// actively try to mark it failed and kill associated containers. Will
    /// replace existing timeout_seconds value.
    public var timeout: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Overrides`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Overrides().with { $0.containerOverrides = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let containerOverrides = CodingKeys(stringValue: "containerOverrides")
      static let taskCount = CodingKeys(stringValue: "taskCount")
      static let timeout = CodingKeys(stringValue: "timeout")

      static let _knownKeys: Set<Swift.String> = [
        "containerOverrides",
        "taskCount",
        "timeout",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [RunJobRequest.Overrides.ContainerOverride].self, forKey: .containerOverrides)
      {
        self.containerOverrides = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .taskCount) {
        self.taskCount = value
      }
      self.timeout = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .timeout)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.containerOverrides, forKey: .containerOverrides)
      try container.encode(self.taskCount, forKey: .taskCount)
      try container.encodeIfPresent(self.timeout, forKey: .timeout)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Per-container override specification.
    public struct ContainerOverride: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The name of the container specified as a DNS_LABEL.
      public var name: Swift.String = Swift.String()

      /// Optional. Arguments to the entrypoint. Will replace existing args for
      /// override.
      public var args: [Swift.String] = []

      /// List of environment variables to set in the container. Will be merged
      /// with existing env for override.
      public var env: [EnvVar] = []

      /// Optional. True if the intention is to clear out existing args list.
      public var clearArgs: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ContainerOverride`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ContainerOverride().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let name = CodingKeys(stringValue: "name")
        static let args = CodingKeys(stringValue: "args")
        static let env = CodingKeys(stringValue: "env")
        static let clearArgs = CodingKeys(stringValue: "clearArgs")

        static let _knownKeys: Set<Swift.String> = [
          "name",
          "args",
          "env",
          "clearArgs",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
          self.name = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .args) {
          self.args = value
        }
        if let value = try container.decodeIfPresent([EnvVar].self, forKey: .env) {
          self.env = value
        }
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .clearArgs) {
          self.clearArgs = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.args, forKey: .args)
        try container.encode(self.env, forKey: .env)
        try container.encode(self.clearArgs, forKey: .clearArgs)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.run.v2.RunJobRequest.Overrides.ContainerOverride"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.run.v2.RunJobRequest.Overrides"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.RunJobRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
