// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The secret's value will be presented as the content of a file whose
/// name is defined in the item path. If no items are defined, the name of
/// the file is the secret.
public struct SecretVolumeSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the secret in Cloud Secret Manager.
  /// Format: {secret} if the secret is in the same project.
  /// projects/{project}/secrets/{secret} if the secret is
  /// in a different project.
  public var secret: Swift.String = Swift.String()

  /// If unspecified, the volume will expose a file whose name is the
  /// secret, relative to VolumeMount.mount_path + VolumeMount.sub_path.
  /// If specified, the key will be used as the version to fetch from Cloud
  /// Secret Manager and the path will be the name of the file exposed in the
  /// volume. When items are defined, they must specify a path and a version.
  public var items: [VersionToPath] = []

  /// Integer representation of mode bits to use on created files by default.
  /// Must be a value between 0000 and 0777 (octal), defaulting to 0444.
  /// Directories within the path are not affected by  this setting.
  ///
  /// Notes
  ///
  /// * Internally, a umask of 0222 will be applied to any non-zero value.
  /// * This is an integer representation of the mode bits. So, the octal
  /// integer value should look exactly as the chmod numeric notation with a
  /// leading zero. Some examples: for chmod 640 (u=rw,g=r), set to 0640 (octal)
  /// or 416 (base-10). For chmod 755 (u=rwx,g=rx,o=rx), set to 0755 (octal) or
  /// 493 (base-10).
  /// * This might be in conflict with other options that affect the
  /// file mode, like fsGroup, and the result can be other mode bits set.
  ///
  /// This might be in conflict with other options that affect the
  /// file mode, like fsGroup, and as a result, other mode bits could be set.
  public var defaultMode: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `SecretVolumeSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecretVolumeSource().with { $0.secret = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.SecretVolumeSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
