// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudWkt
import GoogleIamV1
import GoogleLongrunning
import Logging

/// Cloud Run Service Control Plane API
///
/// @Snippet(path: "ServicesQuickstart")
public protocol Services {
  /// Creates a new Service in a given project and location.
  ///
  /// @Snippet(path: "Services_CreateService")
  func createService(request: CreateServiceRequest) async throws -> GoogleLongrunning.Operation

  /// Gets information about a Service.
  ///
  /// @Snippet(path: "Services_GetService")
  func getService(request: GetServiceRequest) async throws -> GoogleCloudRunV2.Service

  /// Lists Services. Results are sorted by creation time, descending.
  ///
  /// @Snippet(path: "Services_ListServices")
  func listServices(request: ListServicesRequest) async throws
    -> GoogleCloudRunV2.ListServicesResponse

  /// Lists Services. Results are sorted by creation time, descending.
  func listServices(byItem: ListServicesRequest) throws -> any AsyncSequence<Service, Error>

  /// Updates a Service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  func updateService(request: UpdateServiceRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes a Service.
  /// This will cause the Service to stop serving traffic and will delete all
  /// revisions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  func deleteService(request: DeleteServiceRequest) async throws -> GoogleLongrunning.Operation

  /// Gets the IAM Access Control policy currently in effect for the given
  /// Cloud Run Service. This result does not include any inherited policies.
  ///
  /// @Snippet(path: "Services_GetIamPolicy")
  func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Sets the IAM Access control policy for the specified Service. Overwrites
  /// any existing policy.
  ///
  /// @Snippet(path: "Services_SetIamPolicy")
  func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy

  /// Returns permissions that a caller has on the specified Project.
  ///
  /// There are no permissions required for making this API call.
  ///
  /// @Snippet(path: "Services_TestIamPermissions")
  func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  >

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_WaitOperation")
  func waitOperation(request: WaitOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Creates a new Service in a given project and location.
  ///
  /// @Snippet(path: "Services_CreateService")
  func createService(
    request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Gets information about a Service.
  ///
  /// @Snippet(path: "Services_GetService")
  func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Service

  /// Lists Services. Results are sorted by creation time, descending.
  ///
  /// @Snippet(path: "Services_ListServices")
  func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListServicesResponse

  /// Lists Services. Results are sorted by creation time, descending.
  func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Error>

  /// Updates a Service.
  ///
  /// @Snippet(path: "Services_UpdateService")
  func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a Service.
  /// This will cause the Service to stop serving traffic and will delete all
  /// revisions.
  ///
  /// @Snippet(path: "Services_DeleteService")
  func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Gets the IAM Access Control policy currently in effect for the given
  /// Cloud Run Service. This result does not include any inherited policies.
  ///
  /// @Snippet(path: "Services_GetIamPolicy")
  func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Sets the IAM Access control policy for the specified Service. Overwrites
  /// any existing policy.
  ///
  /// @Snippet(path: "Services_SetIamPolicy")
  func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy

  /// Returns permissions that a caller has on the specified Project.
  ///
  /// There are no permissions required for making this API call.
  ///
  /// @Snippet(path: "Services_TestIamPermissions")
  func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Services_WaitOperation")
  func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation
}

extension Clients {
  /// The recommended implementation for ``Services``.
  public class ServicesClient: Services {
    let inner: any ServicesStub

    /// Creates a new `ServicesClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any ServicesStub = try ServicesTransport(options)
      inner = ServicesRetry(inner, options: options)
      if let logger = options.logger {
        inner = ServicesLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `Services.createService`
    public func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createService(request: request, options: options)
    }

    /// See `Services.getService`
    public func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.Service {
      try await self.inner.getService(request: request, options: options)
    }

    /// See `Services.listServices`
    public func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudRunV2.ListServicesResponse {
      try await self.inner.listServices(request: request, options: options)
    }

    /// Lists Services. Results are sorted by creation time, descending.
    public func listServices(
      byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Service, Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListServicesResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listServices(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Services.updateService`
    public func updateService(
      request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateService(request: request, options: options)
    }

    /// See `Services.deleteService`
    public func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteService(request: request, options: options)
    }

    /// See `Services.getIamPolicy`
    public func getIamPolicy(
      request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// See `Services.setIamPolicy`
    public func setIamPolicy(
      request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// See `Services.testIamPermissions`
    public func testIamPermissions(
      request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// See `Services.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `Services.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `Services.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `Services.waitOperation`
    public func waitOperation(
      request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.waitOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension Services {
  public func createService(request: CreateServiceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createService(request: request, options: .init())
  }

  public func createService(
    request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getService(request: GetServiceRequest) async throws -> GoogleCloudRunV2.Service {
    try await self.getService(request: request, options: .init())
  }

  public func getService(
    request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.Service {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listServices(request: ListServicesRequest) async throws
    -> GoogleCloudRunV2.ListServicesResponse
  {
    try await self.listServices(request: request, options: .init())
  }

  public func listServices(
    request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudRunV2.ListServicesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listServices(byItem: ListServicesRequest) throws -> any AsyncSequence<Service, Error>
  {
    try self.listServices(byItem: byItem, options: .init())
  }

  public func listServices(
    byItem: ListServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Service, Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudRunV2.ListServicesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func updateService(request: UpdateServiceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateService(request: request, options: .init())
  }

  public func updateService(
    request: UpdateServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteService(request: DeleteServiceRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteService(request: request, options: .init())
  }

  public func deleteService(
    request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: SetIamPolicyRequest) async throws -> GoogleIamV1.Policy {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> GoogleIamV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIamV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(byItem: ListOperationsRequest) throws -> any AsyncSequence<
    GoogleLongrunning.Operation, Error
  > {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func waitOperation(request: WaitOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.waitOperation(request: request, options: .init())
  }

  public func waitOperation(
    request: WaitOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
