// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Source type for the container.
public struct SourceCode: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The source type.
  public var sourceType: OneOf_SourceType? = nil

  /// Initialize a new instance of `SourceCode`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SourceCode().with { $0.cloudStorageSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case cloudStorageSource = "cloudStorageSource"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var sourceType: OneOf_SourceType? = nil
    let sourceTypeCheckAndSet = {
      if sourceType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'sourceType'"))
      }
      sourceType = $0
    }
    if let cloudStorageSource = try container.decodeIfPresent(
      SourceCode.CloudStorageSource?.self, forKey: .cloudStorageSource)
    {
      try sourceTypeCheckAndSet(.cloudStorageSource(cloudStorageSource))
    }
    self.sourceType = sourceType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.sourceType {
      switch choice {
      case .cloudStorageSource(let value):
        try container.encode(value, forKey: .cloudStorageSource)
      }
    }
  }

  /// Cloud Storage source.
  public struct CloudStorageSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The Cloud Storage bucket name.
    public var bucket: Swift.String = Swift.String()

    /// Required. The Cloud Storage object name.
    public var object: Swift.String = Swift.String()

    /// Optional. The Cloud Storage object generation.
    public var generation: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `CloudStorageSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudStorageSource().with { $0.bucket = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.run.v2.SourceCode.CloudStorageSource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The source type.
  public enum OneOf_SourceType: Codable, Equatable, Sendable {
    /// The source is a Cloud Storage bucket.
    indirect case cloudStorageSource(SourceCode.CloudStorageSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.SourceCode"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
