// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for submitting a Build.
public struct SubmitBuildRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The project and location to build in. Location must be a region,
  /// e.g., 'us-central1' or 'global' if the global builder is to be used.
  /// Format:
  /// `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. Artifact Registry URI to store the built image.
  public var imageUri: Swift.String = Swift.String()

  /// Optional. The service account to use for the build. If not set, the default
  /// Cloud Build service account for the project will be used.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. Name of the Cloud Build Custom Worker Pool that should be used to
  /// build the function. The format of this field is
  /// `projects/{project}/locations/{region}/workerPools/{workerPool}` where
  /// `{project}` and `{region}` are the project id and region respectively where
  /// the worker pool is defined and `{workerPool}` is the short name of the
  /// worker pool.
  public var workerPool: Swift.String = Swift.String()

  /// Optional. Additional tags to annotate the build.
  public var tags: [Swift.String] = []

  /// Optional. The machine type from default pool to use for the build. If left
  /// blank, cloudbuild will use a sensible default. Currently only E2_HIGHCPU_8
  /// is supported. If worker_pool is set, this field will be ignored.
  public var machineType: Swift.String = Swift.String()

  /// Optional. The release track of the client that initiated the build request.
  public var releaseTrack: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Optional. The client that initiated the build request.
  public var client: Swift.String = Swift.String()

  /// Location of source.
  public var source: OneOf_Source? = nil

  /// Build type must be one of the following.
  public var buildType: OneOf_BuildType? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SubmitBuildRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubmitBuildRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let storageSource = CodingKeys(stringValue: "storageSource")
    static let imageUri = CodingKeys(stringValue: "imageUri")
    static let buildpackBuild = CodingKeys(stringValue: "buildpackBuild")
    static let dockerBuild = CodingKeys(stringValue: "dockerBuild")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let workerPool = CodingKeys(stringValue: "workerPool")
    static let tags = CodingKeys(stringValue: "tags")
    static let machineType = CodingKeys(stringValue: "machineType")
    static let releaseTrack = CodingKeys(stringValue: "releaseTrack")
    static let client = CodingKeys(stringValue: "client")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "storageSource",
      "imageUri",
      "buildpackBuild",
      "dockerBuild",
      "serviceAccount",
      "workerPool",
      "tags",
      "machineType",
      "releaseTrack",
      "client",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageUri) {
      self.imageUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .workerPool) {
      self.workerPool = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
      self.tags = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineType) {
      self.machineType = value
    }
    if let value = try container.decodeIfPresent(GoogleApi.LaunchStage.self, forKey: .releaseTrack)
    {
      self.releaseTrack = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .client) {
      self.client = value
    }

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let storageSource = try container.decodeIfPresent(
      StorageSource?.self, forKey: .storageSource)
    {
      try sourceCheckAndSet(.storageSource(storageSource))
    }
    self.source = source

    var buildType: OneOf_BuildType? = nil
    let buildTypeCheckAndSet = {
      if buildType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'buildType'"))
      }
      buildType = $0
    }
    if let buildpackBuild = try container.decodeIfPresent(
      SubmitBuildRequest.BuildpacksBuild?.self, forKey: .buildpackBuild)
    {
      try buildTypeCheckAndSet(.buildpackBuild(buildpackBuild))
    }
    if let dockerBuild = try container.decodeIfPresent(
      SubmitBuildRequest.DockerBuild?.self, forKey: .dockerBuild)
    {
      try buildTypeCheckAndSet(.dockerBuild(dockerBuild))
    }
    self.buildType = buildType
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.imageUri, forKey: .imageUri)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.releaseTrack, forKey: .releaseTrack)
    try container.encode(self.client, forKey: .client)

    if let choice = self.source {
      switch choice {
      case .storageSource(let value):
        try container.encode(value, forKey: .storageSource)
      }
    }

    if let choice = self.buildType {
      switch choice {
      case .buildpackBuild(let value):
        try container.encode(value, forKey: .buildpackBuild)
      case .dockerBuild(let value):
        try container.encode(value, forKey: .dockerBuild)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Build the source using Docker. This means the source has a Dockerfile.
  public struct DockerBuild: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DockerBuild`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DockerBuild().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest.DockerBuild"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Build the source using Buildpacks.
  public struct BuildpacksBuild: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The runtime name, e.g. 'go113'. Leave blank for generic builds.
    @available(*, deprecated)
    public var runtime: Swift.String = Swift.String()

    /// Optional. Name of the function target if the source is a function source.
    /// Required for function builds.
    public var functionTarget: Swift.String = Swift.String()

    /// Optional. cache_image_uri is the GCR/AR URL where the cache image will be
    /// stored. cache_image_uri is optional and omitting it will disable caching.
    /// This URL must be stable across builds. It is used to derive a
    /// build-specific temporary URL by substituting the tag with the build ID.
    /// The build will clean up the temporary image on a best-effort basis.
    public var cacheImageUri: Swift.String = Swift.String()

    /// Optional. The base image to use for the build.
    public var baseImage: Swift.String = Swift.String()

    /// Optional. User-provided build-time environment variables.
    public var environmentVariables: [Swift.String: Swift.String] = [:]

    /// Optional. Whether or not the application container will be enrolled in
    /// automatic base image updates. When true, the application will be built on
    /// a scratch base image, so the base layers can be appended at run time.
    public var enableAutomaticUpdates: Swift.Bool = Swift.Bool()

    /// Optional. project_descriptor stores the path to the project descriptor
    /// file. When empty, it means that there is no project descriptor file in
    /// the source.
    public var projectDescriptor: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BuildpacksBuild`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildpacksBuild().with { $0.runtime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let runtime = CodingKeys(stringValue: "runtime")
      static let functionTarget = CodingKeys(stringValue: "functionTarget")
      static let cacheImageUri = CodingKeys(stringValue: "cacheImageUri")
      static let baseImage = CodingKeys(stringValue: "baseImage")
      static let environmentVariables = CodingKeys(stringValue: "environmentVariables")
      static let enableAutomaticUpdates = CodingKeys(stringValue: "enableAutomaticUpdates")
      static let projectDescriptor = CodingKeys(stringValue: "projectDescriptor")

      static let _knownKeys: Set<Swift.String> = [
        "runtime",
        "functionTarget",
        "cacheImageUri",
        "baseImage",
        "environmentVariables",
        "enableAutomaticUpdates",
        "projectDescriptor",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .runtime) {
        self.runtime = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .functionTarget) {
        self.functionTarget = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cacheImageUri) {
        self.cacheImageUri = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .baseImage) {
        self.baseImage = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .environmentVariables)
      {
        self.environmentVariables = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableAutomaticUpdates)
      {
        self.enableAutomaticUpdates = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectDescriptor) {
        self.projectDescriptor = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.runtime, forKey: .runtime)
      try container.encode(self.functionTarget, forKey: .functionTarget)
      try container.encode(self.cacheImageUri, forKey: .cacheImageUri)
      try container.encode(self.baseImage, forKey: .baseImage)
      try container.encode(self.environmentVariables, forKey: .environmentVariables)
      try container.encode(self.enableAutomaticUpdates, forKey: .enableAutomaticUpdates)
      try container.encode(self.projectDescriptor, forKey: .projectDescriptor)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest.BuildpacksBuild"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Location of source.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Required. Source for the build.
    indirect case storageSource(StorageSource?)
  }

  /// Build type must be one of the following.
  public enum OneOf_BuildType: Codable, Equatable, Sendable {
    /// Build the source using Buildpacks.
    indirect case buildpackBuild(SubmitBuildRequest.BuildpacksBuild?)
    /// Build the source using Docker. This means the source has a Dockerfile.
    indirect case dockerBuild(SubmitBuildRequest.DockerBuild?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
