// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudWkt

/// Request message for submitting a Build.
public struct SubmitBuildRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location to build in. Location must be a region,
  /// e.g., 'us-central1' or 'global' if the global builder is to be used.
  /// Format:
  /// `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. Artifact Registry URI to store the built image.
  public var imageUri: Swift.String = Swift.String()

  /// Optional. The service account to use for the build. If not set, the default
  /// Cloud Build service account for the project will be used.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. Name of the Cloud Build Custom Worker Pool that should be used to
  /// build the function. The format of this field is
  /// `projects/{project}/locations/{region}/workerPools/{workerPool}` where
  /// `{project}` and `{region}` are the project id and region respectively where
  /// the worker pool is defined and `{workerPool}` is the short name of the
  /// worker pool.
  public var workerPool: Swift.String = Swift.String()

  /// Optional. Additional tags to annotate the build.
  public var tags: [Swift.String] = []

  /// Optional. The machine type from default pool to use for the build. If left
  /// blank, cloudbuild will use a sensible default. Currently only E2_HIGHCPU_8
  /// is supported. If worker_pool is set, this field will be ignored.
  public var machineType: Swift.String = Swift.String()

  /// Optional. The release track of the client that initiated the build request.
  public var releaseTrack: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Optional. The client that initiated the build request.
  public var client: Swift.String = Swift.String()

  /// Location of source.
  public var source: OneOf_Source? = nil

  /// Build type must be one of the following.
  public var buildType: OneOf_BuildType? = nil

  /// Initialize a new instance of `SubmitBuildRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubmitBuildRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case parent = "parent"
    case storageSource = "storageSource"
    case imageUri = "imageUri"
    case buildpackBuild = "buildpackBuild"
    case dockerBuild = "dockerBuild"
    case serviceAccount = "serviceAccount"
    case workerPool = "workerPool"
    case tags = "tags"
    case machineType = "machineType"
    case releaseTrack = "releaseTrack"
    case client = "client"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.imageUri = try container.decode(Swift.String.self, forKey: .imageUri)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.workerPool = try container.decode(Swift.String.self, forKey: .workerPool)
    self.tags = try container.decode([Swift.String].self, forKey: .tags)
    self.machineType = try container.decode(Swift.String.self, forKey: .machineType)
    self.releaseTrack = try container.decode(GoogleApi.LaunchStage.self, forKey: .releaseTrack)
    self.client = try container.decode(Swift.String.self, forKey: .client)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let storageSource = try container.decodeIfPresent(
      StorageSource?.self, forKey: .storageSource)
    {
      try sourceCheckAndSet(.storageSource(storageSource))
    }
    self.source = source

    var buildType: OneOf_BuildType? = nil
    let buildTypeCheckAndSet = {
      if buildType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'buildType'"))
      }
      buildType = $0
    }
    if let buildpackBuild = try container.decodeIfPresent(
      SubmitBuildRequest.BuildpacksBuild?.self, forKey: .buildpackBuild)
    {
      try buildTypeCheckAndSet(.buildpackBuild(buildpackBuild))
    }
    if let dockerBuild = try container.decodeIfPresent(
      SubmitBuildRequest.DockerBuild?.self, forKey: .dockerBuild)
    {
      try buildTypeCheckAndSet(.dockerBuild(dockerBuild))
    }
    self.buildType = buildType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.imageUri, forKey: .imageUri)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.workerPool, forKey: .workerPool)
    try container.encode(self.tags, forKey: .tags)
    try container.encode(self.machineType, forKey: .machineType)
    try container.encode(self.releaseTrack, forKey: .releaseTrack)
    try container.encode(self.client, forKey: .client)

    if let choice = self.source {
      switch choice {
      case .storageSource(let value):
        try container.encode(value, forKey: .storageSource)
      }
    }

    if let choice = self.buildType {
      switch choice {
      case .buildpackBuild(let value):
        try container.encode(value, forKey: .buildpackBuild)
      case .dockerBuild(let value):
        try container.encode(value, forKey: .dockerBuild)
      }
    }
  }

  /// Build the source using Docker. This means the source has a Dockerfile.
  public struct DockerBuild: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `DockerBuild`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DockerBuild().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest.DockerBuild"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Build the source using Buildpacks.
  public struct BuildpacksBuild: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The runtime name, e.g. 'go113'. Leave blank for generic builds.
    public var runtime: Swift.String = Swift.String()

    /// Optional. Name of the function target if the source is a function source.
    /// Required for function builds.
    public var functionTarget: Swift.String = Swift.String()

    /// Optional. cache_image_uri is the GCR/AR URL where the cache image will be
    /// stored. cache_image_uri is optional and omitting it will disable caching.
    /// This URL must be stable across builds. It is used to derive a
    /// build-specific temporary URL by substituting the tag with the build ID.
    /// The build will clean up the temporary image on a best-effort basis.
    public var cacheImageUri: Swift.String = Swift.String()

    /// Optional. The base image to use for the build.
    public var baseImage: Swift.String = Swift.String()

    /// Optional. User-provided build-time environment variables.
    public var environmentVariables: [Swift.String: Swift.String] = [:]

    /// Optional. Whether or not the application container will be enrolled in
    /// automatic base image updates. When true, the application will be built on
    /// a scratch base image, so the base layers can be appended at run time.
    public var enableAutomaticUpdates: Swift.Bool = Swift.Bool()

    /// Optional. project_descriptor stores the path to the project descriptor
    /// file. When empty, it means that there is no project descriptor file in
    /// the source.
    public var projectDescriptor: Swift.String = Swift.String()

    /// Initialize a new instance of `BuildpacksBuild`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BuildpacksBuild().with { $0.runtime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest.BuildpacksBuild"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Location of source.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Required. Source for the build.
    indirect case storageSource(StorageSource?)
  }

  /// Build type must be one of the following.
  public enum OneOf_BuildType: Codable, Equatable, Sendable {
    /// Build the source using Buildpacks.
    indirect case buildpackBuild(SubmitBuildRequest.BuildpacksBuild?)
    /// Build the source using Docker. This means the source has a Dockerfile.
    indirect case dockerBuild(SubmitBuildRequest.DockerBuild?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.SubmitBuildRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
