// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// TaskTemplate describes the data a task should have when created
/// from a template.
public struct TaskTemplate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Holds the single container that defines the unit of execution for this
  /// task.
  public var containers: [Container] = []

  /// Optional. A list of Volumes to make available to containers.
  public var volumes: [Volume] = []

  /// Optional. Max allowed time duration the Task may be active before the
  /// system will actively try to mark it failed and kill associated containers.
  /// This applies per attempt of a task, meaning each retry can run for the full
  /// timeout. Defaults to 600 seconds.
  public var timeout: GoogleCloudWkt.Duration? = nil

  /// Optional. Email address of the IAM service account associated with the Task
  /// of a Job. The service account represents the identity of the running task,
  /// and determines what permissions the task has. If not provided, the task
  /// will use the project's default service account.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. The execution environment being used to host this Task.
  public var executionEnvironment: ExecutionEnvironment = ExecutionEnvironment()

  /// A reference to a customer managed encryption key (CMEK) to use to encrypt
  /// this container image. For more information, go to
  /// https://cloud.google.com/run/docs/securing/using-cmek
  public var encryptionKey: Swift.String = Swift.String()

  /// Optional. VPC Access configuration to use for this Task. For more
  /// information, visit
  /// https://cloud.google.com/run/docs/configuring/connecting-vpc.
  public var vpcAccess: VpcAccess? = nil

  /// Optional. The node selector for the task template.
  public var nodeSelector: NodeSelector? = nil

  /// Optional. True if GPU zonal redundancy is disabled on this task template.
  public var gpuZonalRedundancyDisabled: Swift.Bool? = nil

  public var retries: OneOf_Retries? = nil

  /// Initialize a new instance of `TaskTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TaskTemplate().with { $0.containers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case containers = "containers"
    case volumes = "volumes"
    case maxRetries = "maxRetries"
    case timeout = "timeout"
    case serviceAccount = "serviceAccount"
    case executionEnvironment = "executionEnvironment"
    case encryptionKey = "encryptionKey"
    case vpcAccess = "vpcAccess"
    case nodeSelector = "nodeSelector"
    case gpuZonalRedundancyDisabled = "gpuZonalRedundancyDisabled"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.containers = try container.decode([Container].self, forKey: .containers)
    self.volumes = try container.decode([Volume].self, forKey: .volumes)
    self.timeout = try container.decodeIfPresent(GoogleCloudWkt.Duration.self, forKey: .timeout)
    self.serviceAccount = try container.decode(Swift.String.self, forKey: .serviceAccount)
    self.executionEnvironment = try container.decode(
      ExecutionEnvironment.self, forKey: .executionEnvironment)
    self.encryptionKey = try container.decode(Swift.String.self, forKey: .encryptionKey)
    self.vpcAccess = try container.decodeIfPresent(VpcAccess.self, forKey: .vpcAccess)
    self.nodeSelector = try container.decodeIfPresent(NodeSelector.self, forKey: .nodeSelector)
    self.gpuZonalRedundancyDisabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .gpuZonalRedundancyDisabled)

    var retries: OneOf_Retries? = nil
    let retriesCheckAndSet = {
      if retries != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'retries'"))
      }
      retries = $0
    }
    if let maxRetries = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxRetries) {
      try retriesCheckAndSet(.maxRetries(maxRetries))
    }
    self.retries = retries
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containers, forKey: .containers)
    try container.encode(self.volumes, forKey: .volumes)
    try container.encode(self.timeout, forKey: .timeout)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.executionEnvironment, forKey: .executionEnvironment)
    try container.encode(self.encryptionKey, forKey: .encryptionKey)
    try container.encode(self.vpcAccess, forKey: .vpcAccess)
    try container.encode(self.nodeSelector, forKey: .nodeSelector)
    try container.encode(self.gpuZonalRedundancyDisabled, forKey: .gpuZonalRedundancyDisabled)

    if let choice = self.retries {
      switch choice {
      case .maxRetries(let value):
        try container.encode(value, forKey: .maxRetries)
      }
    }
  }

  public enum OneOf_Retries: Codable, Equatable, Sendable {
    /// Number of retries allowed per Task, before marking this Task failed.
    /// Defaults to 3.
    case maxRetries(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.TaskTemplate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
