// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// TaskTemplate describes the data a task should have when created
/// from a template.
public struct TaskTemplate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Holds the single container that defines the unit of execution for this
  /// task.
  public var containers: [Container] = []

  /// Optional. A list of Volumes to make available to containers.
  public var volumes: [Volume] = []

  /// Optional. Max allowed time duration the Task may be active before the
  /// system will actively try to mark it failed and kill associated containers.
  /// This applies per attempt of a task, meaning each retry can run for the full
  /// timeout. Defaults to 600 seconds.
  public var timeout: GoogleWKT.Duration? = nil

  /// Optional. Email address of the IAM service account associated with the Task
  /// of a Job. The service account represents the identity of the running task,
  /// and determines what permissions the task has. If not provided, the task
  /// will use the project's default service account.
  public var serviceAccount: Swift.String = Swift.String()

  /// Optional. The execution environment being used to host this Task.
  public var executionEnvironment: ExecutionEnvironment = ExecutionEnvironment()

  /// A reference to a customer managed encryption key (CMEK) to use to encrypt
  /// this container image. For more information, go to
  /// https://cloud.google.com/run/docs/securing/using-cmek
  public var encryptionKey: Swift.String = Swift.String()

  /// Optional. VPC Access configuration to use for this Task. For more
  /// information, visit
  /// https://cloud.google.com/run/docs/configuring/connecting-vpc.
  public var vpcAccess: VpcAccess? = nil

  /// Optional. The node selector for the task template.
  public var nodeSelector: NodeSelector? = nil

  /// Optional. True if GPU zonal redundancy is disabled on this task template.
  public var gpuZonalRedundancyDisabled: Swift.Bool? = nil

  public var retries: OneOf_Retries? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TaskTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TaskTemplate().with { $0.containers = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let containers = CodingKeys(stringValue: "containers")
    static let volumes = CodingKeys(stringValue: "volumes")
    static let maxRetries = CodingKeys(stringValue: "maxRetries")
    static let timeout = CodingKeys(stringValue: "timeout")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let executionEnvironment = CodingKeys(stringValue: "executionEnvironment")
    static let encryptionKey = CodingKeys(stringValue: "encryptionKey")
    static let vpcAccess = CodingKeys(stringValue: "vpcAccess")
    static let nodeSelector = CodingKeys(stringValue: "nodeSelector")
    static let gpuZonalRedundancyDisabled = CodingKeys(stringValue: "gpuZonalRedundancyDisabled")

    static let _knownKeys: Set<Swift.String> = [
      "containers",
      "volumes",
      "maxRetries",
      "timeout",
      "serviceAccount",
      "executionEnvironment",
      "encryptionKey",
      "vpcAccess",
      "nodeSelector",
      "gpuZonalRedundancyDisabled",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Container].self, forKey: .containers) {
      self.containers = value
    }
    if let value = try container.decodeIfPresent([Volume].self, forKey: .volumes) {
      self.volumes = value
    }
    self.timeout = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .timeout)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(
      ExecutionEnvironment.self, forKey: .executionEnvironment)
    {
      self.executionEnvironment = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .encryptionKey) {
      self.encryptionKey = value
    }
    self.vpcAccess = try container.decodeIfPresent(VpcAccess.self, forKey: .vpcAccess)
    self.nodeSelector = try container.decodeIfPresent(NodeSelector.self, forKey: .nodeSelector)
    self.gpuZonalRedundancyDisabled = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .gpuZonalRedundancyDisabled)

    var retries: OneOf_Retries? = nil
    let retriesCheckAndSet = {
      if retries != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'retries'"))
      }
      retries = $0
    }
    if let maxRetries = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxRetries) {
      try retriesCheckAndSet(.maxRetries(maxRetries))
    }
    self.retries = retries
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containers, forKey: .containers)
    try container.encode(self.volumes, forKey: .volumes)
    try container.encodeIfPresent(self.timeout, forKey: .timeout)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.executionEnvironment, forKey: .executionEnvironment)
    try container.encode(self.encryptionKey, forKey: .encryptionKey)
    try container.encodeIfPresent(self.vpcAccess, forKey: .vpcAccess)
    try container.encodeIfPresent(self.nodeSelector, forKey: .nodeSelector)
    try container.encodeIfPresent(
      self.gpuZonalRedundancyDisabled, forKey: .gpuZonalRedundancyDisabled)

    if let choice = self.retries {
      switch choice {
      case .maxRetries(let value):
        try container.encode(value, forKey: .maxRetries)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Retries: Codable, Equatable, Sendable {
    /// Number of retries allowed per Task, before marking this Task failed.
    /// Defaults to 3.
    case maxRetries(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.TaskTemplate"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
