// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Holds a single traffic routing entry for the Service. Allocations can be done
/// to a specific Revision name, or pointing to the latest Ready Revision.
public struct TrafficTarget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The allocation type for this traffic target.
  public var type: TrafficTargetAllocationType

  /// Revision to which to send this portion of traffic, if traffic allocation is
  /// by revision.
  public var revision: Swift.String

  /// Specifies percent of the traffic to this Revision.
  /// This defaults to zero if unspecified.
  public var percent: Swift.Int32

  /// Indicates a string to be part of the URI to exclusively reference this
  /// target.
  public var tag: Swift.String

  /// Initialize a new instance of `TrafficTarget`.
  public init(
    type: TrafficTargetAllocationType = TrafficTargetAllocationType(),
    revision: Swift.String = Swift.String(),
    percent: Swift.Int32 = Swift.Int32(),
    tag: Swift.String = Swift.String(),
  ) {
    self.type = type
    self.revision = revision
    self.percent = percent
    self.tag = tag
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.run.v2.TrafficTarget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
