// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// VPC Access settings. For more information on sending traffic to a VPC
/// network, visit https://cloud.google.com/run/docs/configuring/connecting-vpc.
public struct VpcAccess: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// VPC Access connector name.
  /// Format: `projects/{project}/locations/{location}/connectors/{connector}`,
  /// where `{project}` can be project id or number.
  /// For more information on sending traffic to a VPC network via a connector,
  /// visit https://cloud.google.com/run/docs/configuring/vpc-connectors.
  public var connector: Swift.String = Swift.String()

  /// Optional. Traffic VPC egress settings. If not provided, it defaults to
  /// PRIVATE_RANGES_ONLY.
  public var egress: VpcAccess.VpcEgress = VpcAccess.VpcEgress()

  /// Optional. Direct VPC egress settings. Currently only single network
  /// interface is supported.
  public var networkInterfaces: [VpcAccess.NetworkInterface] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VpcAccess`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VpcAccess().with { $0.connector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let connector = CodingKeys(stringValue: "connector")
    static let egress = CodingKeys(stringValue: "egress")
    static let networkInterfaces = CodingKeys(stringValue: "networkInterfaces")

    static let _knownKeys: Set<Swift.String> = [
      "connector",
      "egress",
      "networkInterfaces",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .connector) {
      self.connector = value
    }
    if let value = try container.decodeIfPresent(VpcAccess.VpcEgress.self, forKey: .egress) {
      self.egress = value
    }
    if let value = try container.decodeIfPresent(
      [VpcAccess.NetworkInterface].self, forKey: .networkInterfaces)
    {
      self.networkInterfaces = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.connector, forKey: .connector)
    try container.encode(self.egress, forKey: .egress)
    try container.encode(self.networkInterfaces, forKey: .networkInterfaces)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Direct VPC egress settings.
  public struct NetworkInterface: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The VPC network that the Cloud Run resource will be able to
    /// send traffic to. At least one of network or subnetwork must be specified.
    /// If both network and subnetwork are specified, the given VPC subnetwork
    /// must belong to the given VPC network. If network is not specified, it
    /// will be looked up from the subnetwork.
    public var network: Swift.String = Swift.String()

    /// Optional. The VPC subnetwork that the Cloud Run resource will get IPs
    /// from. At least one of network or subnetwork must be specified. If both
    /// network and subnetwork are specified, the given VPC subnetwork must
    /// belong to the given VPC network. If subnetwork is not specified, the
    /// subnetwork with the same name with the network will be used.
    public var subnetwork: Swift.String = Swift.String()

    /// Optional. Network tags applied to this Cloud Run resource.
    public var tags: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NetworkInterface`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NetworkInterface().with { $0.network = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let network = CodingKeys(stringValue: "network")
      static let subnetwork = CodingKeys(stringValue: "subnetwork")
      static let tags = CodingKeys(stringValue: "tags")

      static let _knownKeys: Set<Swift.String> = [
        "network",
        "subnetwork",
        "tags",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
        self.network = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subnetwork) {
        self.subnetwork = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .tags) {
        self.tags = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.network, forKey: .network)
      try container.encode(self.subnetwork, forKey: .subnetwork)
      try container.encode(self.tags, forKey: .tags)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.run.v2.VpcAccess.NetworkInterface"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Egress options for VPC access.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum VpcEgress: Codable, Equatable, Sendable {
    /// Unspecified
    case unspecified
    /// All outbound traffic is routed through the VPC connector.
    case allTraffic
    /// Only private IP ranges are routed through the VPC connector.
    case privateRangesOnly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allTraffic: return 1
      case .privateRangesOnly: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VPC_EGRESS_UNSPECIFIED"
      case .allTraffic: return "ALL_TRAFFIC"
      case .privateRangesOnly: return "PRIVATE_RANGES_ONLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:VpcEgress/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VPC_EGRESS_UNSPECIFIED": self = .unspecified
      case "ALL_TRAFFIC": self = .allTraffic
      case "PRIVATE_RANGES_ONLY": self = .privateRangesOnly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:VpcEgress/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allTraffic
      case 2: self = .privateRangesOnly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VPC_EGRESS_UNSPECIFIED")
      case .allTraffic: return try container.encode("ALL_TRAFFIC")
      case .privateRangesOnly: return try container.encode("PRIVATE_RANGES_ONLY")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.VpcAccess"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
