// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudWkt

/// WorkerPool acts as a top-level container that manages a set of
/// configurations and revision templates which implement a pull-based workload.
/// WorkerPool exists to provide a singular abstraction which can be access
/// controlled, reasoned about, and which encapsulates software lifecycle
/// decisions such as rollout policy and team resource ownership.
public struct WorkerPool: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The fully qualified name of this WorkerPool. In CreateWorkerPoolRequest,
  /// this field is ignored, and instead composed from
  /// CreateWorkerPoolRequest.parent and CreateWorkerPoolRequest.worker_id.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/workerPools/{worker_id}`
  public var name: Swift.String = Swift.String()

  /// User-provided description of the WorkerPool. This field currently has a
  /// 512-character limit.
  public var description: Swift.String = Swift.String()

  /// Output only. Server assigned unique identifier for the trigger. The value
  /// is a UUID4 string and guaranteed to remain unchanged until the resource is
  /// deleted.
  public var uid: Swift.String = Swift.String()

  /// Output only. A number that monotonically increases every time the user
  /// modifies the desired state.
  /// Please note that unlike v1, this is an int64 value. As with most Google
  /// APIs, its JSON representation will be a `string` instead of an `integer`.
  public var generation: Swift.Int64 = Swift.Int64()

  /// Optional. Unstructured key value map that can be used to organize and
  /// categorize objects. User-provided labels are shared with Google's billing
  /// system, so they can be used to filter, or break down billing charges by
  /// team, component, environment, state, etc. For more information, visit
  /// https://cloud.google.com/resource-manager/docs/creating-managing-labels or
  /// https://cloud.google.com/run/docs/configuring/labels.
  ///
  /// Cloud Run API v2 does not support labels with  `run.googleapis.com`,
  /// `cloud.googleapis.com`, `serving.knative.dev`, or `autoscaling.knative.dev`
  /// namespaces, and they will be rejected. All system labels in v1 now have a
  /// corresponding field in v2 WorkerPool.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Unstructured key value map that may be set by external tools to
  /// store and arbitrary metadata. They are not queryable and should be
  /// preserved when modifying objects.
  ///
  /// Cloud Run API v2 does not support annotations with `run.googleapis.com`,
  /// `cloud.googleapis.com`, `serving.knative.dev`, or `autoscaling.knative.dev`
  /// namespaces, and they will be rejected in new resources. All system
  /// annotations in v1 now have a corresponding field in v2 WorkerPool.
  ///
  /// <p>This field follows Kubernetes
  /// annotations' namespacing, limits, and rules.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last-modified time.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The deletion time. It is only populated as a response to a
  /// Delete request.
  public var deleteTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. For a deleted resource, the time after which it will be
  /// permamently deleted.
  public var expireTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Email address of the authenticated creator.
  public var creator: Swift.String = Swift.String()

  /// Output only. Email address of the last authenticated modifier.
  public var lastModifier: Swift.String = Swift.String()

  /// Arbitrary identifier for the API client.
  public var client: Swift.String = Swift.String()

  /// Arbitrary version identifier for the API client.
  public var clientVersion: Swift.String = Swift.String()

  /// Optional. The launch stage as defined by [Google Cloud Platform
  ///  Launch Stages](https://cloud.google.com/terms/launch-stages).
  ///  Cloud Run supports `ALPHA`, `BETA`, and `GA`. If no value is specified, GA
  ///  is assumed.
  ///  Set the launch stage to a preview stage on input to allow use of preview
  ///  features in that stage. On read (or output), describes whether the
  ///  resource uses preview features.
  ///
  ///  For example, if ALPHA is provided as input, but only BETA and GA-level
  ///  features are used, this field will be BETA on output.
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// Optional. Settings for the Binary Authorization feature.
  public var binaryAuthorization: BinaryAuthorization? = nil

  /// Required. The template used to create revisions for this WorkerPool.
  public var template: WorkerPoolRevisionTemplate? = nil

  /// Optional. Specifies how to distribute instances over a collection of
  /// Revisions belonging to the WorkerPool. If instance split is empty or not
  /// provided, defaults to 100% instances assigned to the latest `Ready`
  /// Revision.
  public var instanceSplits: [InstanceSplit] = []

  /// Optional. Specifies worker-pool-level scaling settings
  public var scaling: WorkerPoolScaling? = nil

  /// Output only. The generation of this WorkerPool currently serving workloads.
  /// See comments in `reconciling` for additional information on reconciliation
  /// process in Cloud Run. Please note that unlike v1, this is an int64 value.
  /// As with most Google APIs, its JSON representation will be a `string`
  /// instead of an `integer`.
  public var observedGeneration: Swift.Int64 = Swift.Int64()

  /// Output only. The Condition of this WorkerPool, containing its readiness
  /// status, and detailed error information in case it did not reach a serving
  /// state. See comments in `reconciling` for additional information on
  /// reconciliation process in Cloud Run.
  public var terminalCondition: Condition? = nil

  /// Output only. The Conditions of all other associated sub-resources. They
  /// contain additional diagnostics information in case the WorkerPool does not
  /// reach its Serving state. See comments in `reconciling` for additional
  /// information on reconciliation process in Cloud Run.
  public var conditions: [Condition] = []

  /// Output only. Name of the latest revision that is serving workloads. See
  /// comments in `reconciling` for additional information on reconciliation
  /// process in Cloud Run.
  public var latestReadyRevision: Swift.String = Swift.String()

  /// Output only. Name of the last created revision. See comments in
  /// `reconciling` for additional information on reconciliation process in Cloud
  /// Run.
  public var latestCreatedRevision: Swift.String = Swift.String()

  /// Output only. Detailed status information for corresponding instance splits.
  /// See comments in `reconciling` for additional information on reconciliation
  /// process in Cloud Run.
  public var instanceSplitStatuses: [InstanceSplitStatus] = []

  /// Output only. Indicates whether Cloud Run Threat Detection monitoring is
  /// enabled for the parent project of this worker pool.
  public var threatDetectionEnabled: Swift.Bool = Swift.Bool()

  /// Deprecated: Not supported, and ignored by Cloud Run.
  @available(*, deprecated)
  public var customAudiences: [Swift.String] = []

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. Returns true if the WorkerPool is currently being acted upon
  /// by the system to bring it into the desired state.
  ///
  /// When a new WorkerPool is created, or an existing one is updated, Cloud Run
  /// will asynchronously perform all necessary steps to bring the WorkerPool to
  /// the desired serving state. This process is called reconciliation. While
  /// reconciliation is in process, `observed_generation`,
  /// `latest_ready_revison`, `instance_split_statuses`, and `uri` will have
  /// transient values that might mismatch the intended state: Once
  /// reconciliation is over (and this field is false), there are two possible
  /// outcomes: reconciliation succeeded and the serving state matches the
  /// WorkerPool, or there was an error, and reconciliation failed. This state
  /// can be found in `terminal_condition.state`.
  ///
  /// If reconciliation succeeded, the following fields will match:
  /// `instance_splits` and `instance_split_statuses`, `observed_generation` and
  /// `generation`, `latest_ready_revision` and `latest_created_revision`.
  ///
  /// If reconciliation failed, `instance_split_statuses`, `observed_generation`,
  /// and `latest_ready_revision` will have the state of the last serving
  /// revision, or empty for newly created WorkerPools. Additional information on
  /// the failure can be found in `terminal_condition` and `conditions`.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. A system-generated fingerprint for this version of the
  /// resource. May be used to detect modification conflict during updates.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `WorkerPool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkerPool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.WorkerPool"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
