// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// WorkerPoolRevisionTemplate describes the data a worker pool revision should
/// have when created from a template.
public struct WorkerPoolRevisionTemplate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The unique name for the revision. If this field is omitted, it
  /// will be automatically generated based on the WorkerPool name.
  public var revision: Swift.String = Swift.String()

  /// Optional. Unstructured key value map that can be used to organize and
  /// categorize objects. User-provided labels are shared with Google's billing
  /// system, so they can be used to filter, or break down billing charges by
  /// team, component, environment, state, etc. For more information, visit
  /// https://cloud.google.com/resource-manager/docs/creating-managing-labels or
  /// https://cloud.google.com/run/docs/configuring/labels.
  ///
  /// Cloud Run API v2 does not support labels with `run.googleapis.com`,
  /// `cloud.googleapis.com`, `serving.knative.dev`, or `autoscaling.knative.dev`
  /// namespaces, and they will be rejected. All system labels in v1 now have a
  /// corresponding field in v2 WorkerPoolRevisionTemplate.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Unstructured key value map that may be set by external tools to
  /// store and arbitrary metadata. They are not queryable and should be
  /// preserved when modifying objects.
  ///
  /// Cloud Run API v2 does not support annotations with `run.googleapis.com`,
  /// `cloud.googleapis.com`, `serving.knative.dev`, or `autoscaling.knative.dev`
  /// namespaces, and they will be rejected. All system annotations in v1 now
  /// have a corresponding field in v2 WorkerPoolRevisionTemplate.
  ///
  /// This field follows Kubernetes annotations' namespacing, limits, and
  /// rules.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. VPC Access configuration to use for this Revision. For more
  /// information, visit
  /// https://cloud.google.com/run/docs/configuring/connecting-vpc.
  public var vpcAccess: VpcAccess? = nil

  /// Optional. Email address of the IAM service account associated with the
  /// revision of the service. The service account represents the identity of the
  /// running revision, and determines what permissions the revision has. If not
  /// provided, the revision will use the project's default service account.
  public var serviceAccount: Swift.String = Swift.String()

  /// Holds list of the containers that defines the unit of execution for this
  /// Revision.
  public var containers: [Container] = []

  /// Optional. A list of Volumes to make available to containers.
  public var volumes: [Volume] = []

  /// A reference to a customer managed encryption key (CMEK) to use to encrypt
  /// this container image. For more information, go to
  /// https://cloud.google.com/run/docs/securing/using-cmek
  public var encryptionKey: Swift.String = Swift.String()

  /// Optional. Enables service mesh connectivity.
  public var serviceMesh: ServiceMesh? = nil

  /// Optional. The action to take if the encryption key is revoked.
  public var encryptionKeyRevocationAction: EncryptionKeyRevocationAction =
    EncryptionKeyRevocationAction()

  /// Optional. If encryption_key_revocation_action is SHUTDOWN, the duration
  /// before shutting down all instances. The minimum increment is 1 hour.
  public var encryptionKeyShutdownDuration: GoogleCloudWkt.Duration? = nil

  /// Optional. The node selector for the revision template.
  public var nodeSelector: NodeSelector? = nil

  /// Optional. True if GPU zonal redundancy is disabled on this worker pool.
  public var gpuZonalRedundancyDisabled: Swift.Bool? = nil

  /// Initialize a new instance of `WorkerPoolRevisionTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkerPoolRevisionTemplate().with { $0.revision = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.run.v2.WorkerPoolRevisionTemplate"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
